### ISSUE TITLE
Incorrect Link to CBC Page

### ISSUE THREAD

**Issue by olliegilbey** [CudoVentures/cudos-docs#41]
https://github.com/CudoVentures/cudos-docs/blob/5c1434ed8d1d85c7d0b15b7e54b93f9fb6ab9732/docs/blockchain-compute/usage/via-user-interface/signing-in.md?plain=1#L8

**Comment by nbaum** [comment]
Fixed in f052c73607da300e2357451ea2c105f78b98f98b
